mybatis:
  configuration:
    call-setters-on-nulls: 'true'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/duzhicheng/cloud/com/duzhicheng/cloud/dao/user/mapper/*.xml
  type-aliases-package: springcloudentity.springcloudentity.entity
eureka:
  client:
    service-url:
      defaultZone: http://server1:9900/eureka/,http://server2:9901/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: lh123
    url: jdbc:mysql://192.168.1.8:3306/lh?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: lh
